import { IOption } from "./types";

export const SETTINGS: IOption[] = [
  {gcode: '$0', value: 0, label: 'Длительность импульса Step, мкс', description: ''},
  {gcode: '$1', value: 0, label: 'Задержка откл. ШД, мс', description: ''},
  {gcode: '$2', value: 0, label: 'Инверсия порта шаговых испульсов', description: ''},
  {gcode: '$3', value: 0, label: 'Инверсия направления, маска', description: ''},
  {gcode: '$4', value: 0, label: 'Инверсия сигнала включения шаговых двигателей', description: ''},
  {gcode: '$5', value: 0, label: 'Инверсия входов концевых выключателей', description: ''},
  {gcode: '$6', value: 0, label: 'Инверсия входа контактного датчика, логический', description: ''},
  {gcode: '$10', value: 0, label: 'Отчет о состоянии', description: ''},
  {gcode: '$11', value: 0, label: 'Отклонение на стыках, мм', description: ''},
  {gcode: '$12', value: 0, label: 'Отклонение от дуги, мм', description: ''},
  {gcode: '$13', value: 0, label: 'Отчет в дюймах', description: ''},
  {gcode: '$20', value: 0, label: 'Мягкие границы', description: ''},
  {gcode: '$21', value: 0, label: 'Жесткие границы', description: ''},
  {gcode: '$22', value: 0, label: 'Поиск начальной позиции', description: ''},
  {gcode: '$23', value: 0, label: 'Инверсия направления начальной точки', description: ''},
  {gcode: '$24', value: 0, label: 'Скорость подачи при поиске начальной точки, мм/мин', description: ''},
  {gcode: '$25', value: 0, label: 'Скорость поиска начальной точки, мм/мин', description: ''},
  {gcode: '$26', value: 0, label: 'Подавление дребезга при поиске начальной точки, миллисекунд', description: ''},
  {gcode: '$27', value: 0, label: 'Отъезд от начальной точки, мм', description: ''},
  {gcode: '$30', value: 0, label: 'Максимальные обороты шпинделя, Об/мин', description: ''},
  {gcode: '$31', value: 0, label: 'Минимальные обороты шпинделя, Об/мин', description: ''},
  {gcode: '$32', value: 0, label: 'Режим лазера', description: ''},
  {gcode: '$100', value: 0, label: 'Кол-во шагов на мм для оси Х', description: ''},
  {gcode: '$101', value: 0, label: 'Кол-во шагов на мм для оси Y', description: ''},
  {gcode: '$102', value: 0, label: 'Кол-во шагов на мм для оси Z', description: ''},
  {gcode: '$110', value: 0, label: 'Максимальная скорость оси Х, мм/мин', description: ''},
  {gcode: '$111', value: 0, label: 'Максимальная скорость оси Y, мм/мин', description: ''},
  {gcode: '$112', value: 0, label: 'Максимальная скорость оси Z, мм/мин', description: ''},
  {gcode: '$120', value: 0, label: 'Ускорение оси Х, мм/сек^2', description: ''},
  {gcode: '$121', value: 0, label: 'Ускорение оси Y, мм/сек^2', description: ''},
  {gcode: '$122', value: 0, label: 'Ускорение оси Z, мм/сек^2', description: ''},
  {gcode: '$130', value: 0, label: 'Максимальное перемещение оси Х, мм', description: ''},
  {gcode: '$131', value: 0, label: 'Максимальное перемещение оси Y, мм', description: ''},
  {gcode: '$132', value: 0, label: 'Максимальное перемещение оси Z, мм', description: ''},
]